// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go
//
// Generated by this command:
//
//	mockgen --source=handlers.go --destination=mocks/handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pullrequests "github.com/qwerty268/pull_request_service/internal/usecases/pullrequests"
	gomock "go.uber.org/mock/gomock"
)

// MockPRCreator is a mock of PRCreator interface.
type MockPRCreator struct {
	ctrl     *gomock.Controller
	recorder *MockPRCreatorMockRecorder
	isgomock struct{}
}

// MockPRCreatorMockRecorder is the mock recorder for MockPRCreator.
type MockPRCreatorMockRecorder struct {
	mock *MockPRCreator
}

// NewMockPRCreator creates a new mock instance.
func NewMockPRCreator(ctrl *gomock.Controller) *MockPRCreator {
	mock := &MockPRCreator{ctrl: ctrl}
	mock.recorder = &MockPRCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRCreator) EXPECT() *MockPRCreatorMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockPRCreator) CreatePR(ctx context.Context, pr pullrequests.CreatePROpst) (*pullrequests.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, pr)
	ret0, _ := ret[0].(*pullrequests.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPRCreatorMockRecorder) CreatePR(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPRCreator)(nil).CreatePR), ctx, pr)
}

// MergePR mocks base method.
func (m *MockPRCreator) MergePR(ctx context.Context, prID string) (*pullrequests.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, prID)
	ret0, _ := ret[0].(*pullrequests.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPRCreatorMockRecorder) MergePR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPRCreator)(nil).MergePR), ctx, prID)
}

// ReassignReviewer mocks base method.
func (m *MockPRCreator) ReassignReviewer(ctx context.Context, prID, oldUserID string) (*pullrequests.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldUserID)
	ret0, _ := ret[0].(*pullrequests.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPRCreatorMockRecorder) ReassignReviewer(ctx, prID, oldUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPRCreator)(nil).ReassignReviewer), ctx, prID, oldUserID)
}
