// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go
//
// Generated by this command:
//
//	mockgen --source=handlers.go --destination=mocks/handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	teams "github.com/qwerty268/pull_request_service/internal/usecases/teams"
	gomock "go.uber.org/mock/gomock"
)

// MockGetter is a mock of Getter interface.
type MockGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGetterMockRecorder
	isgomock struct{}
}

// MockGetterMockRecorder is the mock recorder for MockGetter.
type MockGetterMockRecorder struct {
	mock *MockGetter
}

// NewMockGetter creates a new mock instance.
func NewMockGetter(ctrl *gomock.Controller) *MockGetter {
	mock := &MockGetter{ctrl: ctrl}
	mock.recorder = &MockGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetter) EXPECT() *MockGetterMockRecorder {
	return m.recorder
}

// AddTeam mocks base method.
func (m *MockGetter) AddTeam(ctx context.Context, team teams.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTeam indicates an expected call of AddTeam.
func (mr *MockGetterMockRecorder) AddTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*MockGetter)(nil).AddTeam), ctx, team)
}

// GetTeam mocks base method.
func (m *MockGetter) GetTeam(ctx context.Context, teamName string) (*teams.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(*teams.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockGetterMockRecorder) GetTeam(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockGetter)(nil).GetTeam), ctx, teamName)
}
