// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen --source=usecase.go --destination=mocks/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	storage "github.com/qwerty268/pull_request_service/internal/usecases/teams/storage"
	gomock "go.uber.org/mock/gomock"
)

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
	isgomock struct{}
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// AddTeam mocks base method.
func (m *Mockstorage) AddTeam(team storage.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTeam", team)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTeam indicates an expected call of AddTeam.
func (mr *MockstorageMockRecorder) AddTeam(team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTeam", reflect.TypeOf((*Mockstorage)(nil).AddTeam), team)
}

// GetTeam mocks base method.
func (m *Mockstorage) GetTeam(teamName string) (*storage.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", teamName)
	ret0, _ := ret[0].(*storage.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockstorageMockRecorder) GetTeam(teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*Mockstorage)(nil).GetTeam), teamName)
}
