// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen --source=usecase.go --destination=mocks/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	storage "github.com/qwerty268/pull_request_service/internal/usecases/users/storage"
	gomock "go.uber.org/mock/gomock"
)

// Mockstorage is a mock of storage interface.
type Mockstorage struct {
	ctrl     *gomock.Controller
	recorder *MockstorageMockRecorder
	isgomock struct{}
}

// MockstorageMockRecorder is the mock recorder for Mockstorage.
type MockstorageMockRecorder struct {
	mock *Mockstorage
}

// NewMockstorage creates a new mock instance.
func NewMockstorage(ctrl *gomock.Controller) *Mockstorage {
	mock := &Mockstorage{ctrl: ctrl}
	mock.recorder = &MockstorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockstorage) EXPECT() *MockstorageMockRecorder {
	return m.recorder
}

// GetUserReviewRequests mocks base method.
func (m *Mockstorage) GetUserReviewRequests(userID string) ([]storage.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviewRequests", userID)
	ret0, _ := ret[0].([]storage.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviewRequests indicates an expected call of GetUserReviewRequests.
func (mr *MockstorageMockRecorder) GetUserReviewRequests(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviewRequests", reflect.TypeOf((*Mockstorage)(nil).GetUserReviewRequests), userID)
}

// SetUserActive mocks base method.
func (m *Mockstorage) SetUserActive(userID string, isActive bool) (*storage.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActive", userID, isActive)
	ret0, _ := ret[0].(*storage.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActive indicates an expected call of SetUserActive.
func (mr *MockstorageMockRecorder) SetUserActive(userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActive", reflect.TypeOf((*Mockstorage)(nil).SetUserActive), userID, isActive)
}
