// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen --source=usecase.go --destination=mocks/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	storage "github.com/qwerty268/pull_request_service/internal/usecases/pullrequests/storage"
	storage0 "github.com/qwerty268/pull_request_service/internal/usecases/users/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockuserStorage is a mock of userStorage interface.
type MockuserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserStorageMockRecorder
	isgomock struct{}
}

// MockuserStorageMockRecorder is the mock recorder for MockuserStorage.
type MockuserStorageMockRecorder struct {
	mock *MockuserStorage
}

// NewMockuserStorage creates a new mock instance.
func NewMockuserStorage(ctrl *gomock.Controller) *MockuserStorage {
	mock := &MockuserStorage{ctrl: ctrl}
	mock.recorder = &MockuserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStorage) EXPECT() *MockuserStorageMockRecorder {
	return m.recorder
}

// SetUserActive mocks base method.
func (m *MockuserStorage) SetUserActive(userID string, isActive bool) (*storage0.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActive", userID, isActive)
	ret0, _ := ret[0].(*storage0.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActive indicates an expected call of SetUserActive.
func (mr *MockuserStorageMockRecorder) SetUserActive(userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActive", reflect.TypeOf((*MockuserStorage)(nil).SetUserActive), userID, isActive)
}

// MockprStorage is a mock of prStorage interface.
type MockprStorage struct {
	ctrl     *gomock.Controller
	recorder *MockprStorageMockRecorder
	isgomock struct{}
}

// MockprStorageMockRecorder is the mock recorder for MockprStorage.
type MockprStorageMockRecorder struct {
	mock *MockprStorage
}

// NewMockprStorage creates a new mock instance.
func NewMockprStorage(ctrl *gomock.Controller) *MockprStorage {
	mock := &MockprStorage{ctrl: ctrl}
	mock.recorder = &MockprStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprStorage) EXPECT() *MockprStorageMockRecorder {
	return m.recorder
}

// GetUserReviewRequests mocks base method.
func (m *MockprStorage) GetUserReviewRequests(userID string) ([]storage.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviewRequests", userID)
	ret0, _ := ret[0].([]storage.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviewRequests indicates an expected call of GetUserReviewRequests.
func (mr *MockprStorageMockRecorder) GetUserReviewRequests(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviewRequests", reflect.TypeOf((*MockprStorage)(nil).GetUserReviewRequests), userID)
}
