// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen --source=usecase.go --destination=mocks/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	storage "github.com/qwerty268/pull_request_service/internal/usecases/pullrequests/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockprStorage is a mock of prStorage interface.
type MockprStorage struct {
	ctrl     *gomock.Controller
	recorder *MockprStorageMockRecorder
	isgomock struct{}
}

// MockprStorageMockRecorder is the mock recorder for MockprStorage.
type MockprStorageMockRecorder struct {
	mock *MockprStorage
}

// NewMockprStorage creates a new mock instance.
func NewMockprStorage(ctrl *gomock.Controller) *MockprStorage {
	mock := &MockprStorage{ctrl: ctrl}
	mock.recorder = &MockprStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprStorage) EXPECT() *MockprStorageMockRecorder {
	return m.recorder
}

// AddPr mocks base method.
func (m *MockprStorage) AddPr(pr storage.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPr", pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPr indicates an expected call of AddPr.
func (mr *MockprStorageMockRecorder) AddPr(pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPr", reflect.TypeOf((*MockprStorage)(nil).AddPr), pr)
}

// CheckUserInPr mocks base method.
func (m *MockprStorage) CheckUserInPr(prID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserInPr", prID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserInPr indicates an expected call of CheckUserInPr.
func (mr *MockprStorageMockRecorder) CheckUserInPr(prID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserInPr", reflect.TypeOf((*MockprStorage)(nil).CheckUserInPr), prID, userID)
}

// GetPrByID mocks base method.
func (m *MockprStorage) GetPrByID(prID string) (*storage.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrByID", prID)
	ret0, _ := ret[0].(*storage.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrByID indicates an expected call of GetPrByID.
func (mr *MockprStorageMockRecorder) GetPrByID(prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrByID", reflect.TypeOf((*MockprStorage)(nil).GetPrByID), prID)
}

// ResetPrMember mocks base method.
func (m *MockprStorage) ResetPrMember(filter storage.ResetReviewerFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPrMember", filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPrMember indicates an expected call of ResetPrMember.
func (mr *MockprStorageMockRecorder) ResetPrMember(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPrMember", reflect.TypeOf((*MockprStorage)(nil).ResetPrMember), filter)
}

// SetPrMerged mocks base method.
func (m *MockprStorage) SetPrMerged(prID string) (*storage.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPrMerged", prID)
	ret0, _ := ret[0].(*storage.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPrMerged indicates an expected call of SetPrMerged.
func (mr *MockprStorageMockRecorder) SetPrMerged(prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrMerged", reflect.TypeOf((*MockprStorage)(nil).SetPrMerged), prID)
}

// MockteamStorage is a mock of teamStorage interface.
type MockteamStorage struct {
	ctrl     *gomock.Controller
	recorder *MockteamStorageMockRecorder
	isgomock struct{}
}

// MockteamStorageMockRecorder is the mock recorder for MockteamStorage.
type MockteamStorageMockRecorder struct {
	mock *MockteamStorage
}

// NewMockteamStorage creates a new mock instance.
func NewMockteamStorage(ctrl *gomock.Controller) *MockteamStorage {
	mock := &MockteamStorage{ctrl: ctrl}
	mock.recorder = &MockteamStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamStorage) EXPECT() *MockteamStorageMockRecorder {
	return m.recorder
}

// CheckUserInCommand mocks base method.
func (m *MockteamStorage) CheckUserInCommand(userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserInCommand", userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserInCommand indicates an expected call of CheckUserInCommand.
func (mr *MockteamStorageMockRecorder) CheckUserInCommand(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserInCommand", reflect.TypeOf((*MockteamStorage)(nil).CheckUserInCommand), userID)
}

// GetUserActiveTeammates mocks base method.
func (m *MockteamStorage) GetUserActiveTeammates(userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActiveTeammates", userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActiveTeammates indicates an expected call of GetUserActiveTeammates.
func (mr *MockteamStorageMockRecorder) GetUserActiveTeammates(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActiveTeammates", reflect.TypeOf((*MockteamStorage)(nil).GetUserActiveTeammates), userID)
}

// MockuserStorage is a mock of userStorage interface.
type MockuserStorage struct {
	ctrl     *gomock.Controller
	recorder *MockuserStorageMockRecorder
	isgomock struct{}
}

// MockuserStorageMockRecorder is the mock recorder for MockuserStorage.
type MockuserStorageMockRecorder struct {
	mock *MockuserStorage
}

// NewMockuserStorage creates a new mock instance.
func NewMockuserStorage(ctrl *gomock.Controller) *MockuserStorage {
	mock := &MockuserStorage{ctrl: ctrl}
	mock.recorder = &MockuserStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStorage) EXPECT() *MockuserStorageMockRecorder {
	return m.recorder
}

// CheckUserExists mocks base method.
func (m *MockuserStorage) CheckUserExists(userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUserExists", userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUserExists indicates an expected call of CheckUserExists.
func (mr *MockuserStorageMockRecorder) CheckUserExists(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUserExists", reflect.TypeOf((*MockuserStorage)(nil).CheckUserExists), userID)
}
