// Code generated by MockGen. DO NOT EDIT.
// Source: handlers.go
//
// Generated by this command:
//
//	mockgen --source=handlers.go --destination=mocks/handlers.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	users "github.com/qwerty268/pull_request_service/internal/usecases/users"
	gomock "go.uber.org/mock/gomock"
)

// MockUserGetter is a mock of UserGetter interface.
type MockUserGetter struct {
	ctrl     *gomock.Controller
	recorder *MockUserGetterMockRecorder
	isgomock struct{}
}

// MockUserGetterMockRecorder is the mock recorder for MockUserGetter.
type MockUserGetterMockRecorder struct {
	mock *MockUserGetter
}

// NewMockUserGetter creates a new mock instance.
func NewMockUserGetter(ctrl *gomock.Controller) *MockUserGetter {
	mock := &MockUserGetter{ctrl: ctrl}
	mock.recorder = &MockUserGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGetter) EXPECT() *MockUserGetterMockRecorder {
	return m.recorder
}

// GetUserReviewRequests mocks base method.
func (m *MockUserGetter) GetUserReviewRequests(ctx context.Context, userID string) ([]users.PullRequestShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviewRequests", ctx, userID)
	ret0, _ := ret[0].([]users.PullRequestShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviewRequests indicates an expected call of GetUserReviewRequests.
func (mr *MockUserGetterMockRecorder) GetUserReviewRequests(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviewRequests", reflect.TypeOf((*MockUserGetter)(nil).GetUserReviewRequests), ctx, userID)
}

// SetUserActive mocks base method.
func (m *MockUserGetter) SetUserActive(ctx context.Context, userID string, isActive bool) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActive", ctx, userID, isActive)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActive indicates an expected call of SetUserActive.
func (mr *MockUserGetterMockRecorder) SetUserActive(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActive", reflect.TypeOf((*MockUserGetter)(nil).SetUserActive), ctx, userID, isActive)
}
